structure(list(url = "projects/123/stories/154237097/", status_code = 204L, 
    headers = structure(list(`access-control-allow-credentials` = "false", 
        `access-control-allow-headers` = "X-TrackerToken,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Tracker-Warn-Unless-Project-Version-Is", 
        `access-control-allow-methods` = "GET, POST, PUT, DELETE, OPTIONS", 
        `access-control-allow-origin` = "*", `cache-control` = "no-cache", 
        date = "Thu, 11 Jan 2018 05:48:19 GMT", server = "nginx + Phusion Passenger", 
        status = "204 No Content", `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        `x-content-type-options` = "nosniff", `x-powered-by` = "Phusion Passenger Enterprise", 
        `x-rack-cache` = "invalidate, pass", `x-request-id` = "9ef6e88fcea967d6a224f99bce1b2cef", 
        `x-runtime` = "0.222048", `x-tracker-client-pinger-interval` = "20", 
        `x-tracker-project-version` = "52", `x-ua-compatible` = "IE=Edge,chrome=1", 
        `x-vcap-request-id` = "0b246351-27d0-494c-58a0-8298d5691e08", 
        `x-xss-protection` = "1; mode=block", via = "1.1 google", 
        `alt-svc` = "clear"), .Names = c("access-control-allow-credentials", 
    "access-control-allow-headers", "access-control-allow-methods", 
    "access-control-allow-origin", "cache-control", "date", "server", 
    "status", "strict-transport-security", "x-content-type-options", 
    "x-powered-by", "x-rack-cache", "x-request-id", "x-runtime", 
    "x-tracker-client-pinger-interval", "x-tracker-project-version", 
    "x-ua-compatible", "x-vcap-request-id", "x-xss-protection", 
    "via", "alt-svc"), class = c("insensitive", "list")), all_headers = list(
        structure(list(status = 204L, version = "HTTP/1.1", headers = structure(list(
            `access-control-allow-credentials` = "false", `access-control-allow-headers` = "X-TrackerToken,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Tracker-Warn-Unless-Project-Version-Is", 
            `access-control-allow-methods` = "GET, POST, PUT, DELETE, OPTIONS", 
            `access-control-allow-origin` = "*", `cache-control` = "no-cache", 
            date = "Thu, 11 Jan 2018 05:48:19 GMT", server = "nginx + Phusion Passenger", 
            status = "204 No Content", `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
            `x-content-type-options` = "nosniff", `x-powered-by` = "Phusion Passenger Enterprise", 
            `x-rack-cache` = "invalidate, pass", `x-request-id` = "9ef6e88fcea967d6a224f99bce1b2cef", 
            `x-runtime` = "0.222048", `x-tracker-client-pinger-interval` = "20", 
            `x-tracker-project-version` = "52", `x-ua-compatible` = "IE=Edge,chrome=1", 
            `x-vcap-request-id` = "0b246351-27d0-494c-58a0-8298d5691e08", 
            `x-xss-protection` = "1; mode=block", via = "1.1 google", 
            `alt-svc` = "clear"), .Names = c("access-control-allow-credentials", 
        "access-control-allow-headers", "access-control-allow-methods", 
        "access-control-allow-origin", "cache-control", "date", 
        "server", "status", "strict-transport-security", "x-content-type-options", 
        "x-powered-by", "x-rack-cache", "x-request-id", "x-runtime", 
        "x-tracker-client-pinger-interval", "x-tracker-project-version", 
        "x-ua-compatible", "x-vcap-request-id", "x-xss-protection", 
        "via", "alt-svc"), class = c("insensitive", "list"))), .Names = c("status", 
        "version", "headers"))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), .Names = c("domain", 
    "flag", "path", "secure", "expiration", "name", "value"), row.names = integer(0), class = "data.frame"), 
    content = raw(0), date = structure(1515649699, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = structure(c(0, 3e-05, 
    3.2e-05, 8.6e-05, 0.385684, 0.385753), .Names = c("redirect", 
    "namelookup", "connect", "pretransfer", "starttransfer", 
    "total")), request = structure(list(method = "DELETE", url = "projects/123/stories/154237097/", 
        headers = structure(c("application/json, text/xml, application/xml, */*", 
        "", "libcurl/7.54.0 curl/3.0 httr/1.3.1 pivotaltrackR/0.1.0", 
        "REDACTED"), .Names = c("Accept", "Content-Type", "user-agent", 
        "X-TrackerToken")), options = structure(list(useragent = "libcurl/7.54.0 r-curl/3.0 httr/1.3.1", 
            post = TRUE, postfieldsize = 0L, customrequest = "DELETE"), .Names = c("useragent", 
        "post", "postfieldsize", "customrequest")), auth_token = NULL, 
        output = structure(list(), class = c("write_memory", 
        "write_function"))), .Names = c("method", "url", "headers", 
    "options", "auth_token", "output"), class = "request")), .Names = c("url", 
"status_code", "headers", "all_headers", "cookies", "content", 
"date", "times", "request"), class = "response")
